### ISSUE TITLE
Some problems with Menaion and Monomakh fonts

### ISSUE THREAD

**Issue by tuffnatty** [typiconman/fonts-cu#25]
While typesetting an article using your excellent font collection, I encountered some problems which are best described [here](http://newstar.rinet.ru/~phil/menaion-monomakh-bugs.pdf).

**Comment by typiconman** [comment]
Copying the file into this thread.

[menaion-monomakh-bugs.pdf](https://github.com/typiconman/fonts-cu/files/850524/menaion-monomakh-bugs.pdf)

**Comment by typiconman** [comment]
I started to work on this. I think I've resolved the issues with the rtsy and the Uk in Monomakh. I will work on this some more over the next few days.
![untitled](https://cloud.githubusercontent.com/assets/5428695/25784071/342c581a-3370-11e7-92f0-ec89f5ef97c3.png)

**Comment by typiconman** [comment]
The correct positioning of double titlos is something that is difficult to do. Consider these examples:

д͠ш <-- here the titlo needs to shift right of center
ш͠д <-- here the titlo needs to shift left of center
ш͠ш <--- here the titlo is exactly centered (the only case that currently works correctly).

This is also related to issue #3 

Thus I am inclined to not support double titlo positioning. Titlo halves are slightly easier to implement. But they need to have different lengths depending on the base glyph. It may be possible to implement this eventually using OpenType Variations. However AFAICT, FontForge does not yet have support for variations. 

Anyway, as I see it, implementing correct positioning of double and triple titlos is a pain, and is not really worth the effort. Unless someone has got a lot of ancient text with double and triple titlos that they are typesetting and can convince me otherwise ...

For now I will try to make sure there are no obvious problems, such as in the examples you submitted.

**Comment by typiconman** [comment]
I think this issue is now resolved. @tuffnatty can you verify? A fresh version of Menaion and Monomakh are attached.
[MenaionUnicode.zip](https://github.com/typiconman/fonts-cu/files/1058972/MenaionUnicode.zip)
[MonomakhUnicode.zip](https://github.com/typiconman/fonts-cu/files/1058974/MonomakhUnicode.zip)

**Comment by typiconman** [comment]
@tuffnatty Can this issue be closed?

**Comment by tuffnatty** [comment]
@typiconman oops sorry for late answer. Yes everything except half and double titlos is working well with the versions attached above.

**Comment by typiconman** [comment]
Closed as fixed. For half marks, see issue #3.
