### ISSUE TITLE
Superscript Glagolitic not working in Menaion

### ISSUE THREAD

**Issue by aleslavista** [typiconman/fonts-cu#32]
Hello,

In LibreOffice Writer 5.4.1.2, Menaion Unicode (both ttf and otf) doesn't display properly Glagolitic superscript characters, while Cyrillic superscript does work.

See attachment
![superscript](https://user-images.githubusercontent.com/33322424/32338412-ebbae0ee-bff4-11e7-87ed-65ef653aaaa0.png)
.

Regards,

**Comment by typiconman** [comment]
I can confirm the bug, but I'm not sure why it happens. The positioning works correctly in Firefox and XeTeX.

Needs to be investigated further.

**Comment by typiconman** [comment]
I think the issue is with LO, which seems to offer no support for Glagolitic:
![test](https://user-images.githubusercontent.com/5428695/32437676-27991df4-c2f9-11e7-8c9e-d3bd783f89c6.png)

It sounds like a bug against LO. The offending file may be here:
https://gerrit.libreoffice.org/gitweb?p=core.git;a=blob;f=i18nutil/source/utility/unicode_data.h;h=bae66cd3f7b87d8b484f5f3431d82f567722e310;hb=HEAD
but I will need to test compiling LO from source (which will take a long time) to confirm.

**Comment by KrasnayaPloshchad** [comment]
LibreOffice seems having a bug that affect handling Unicode properties, because I have found LibreOffice failed to make Tangut and Yi (Nuosu) characters rotated in vertical layout, so I think this Glagolitic may have also been affected by this.

**Comment by typiconman** [comment]
I filed an bug report for LibreOffice:
https://bugs.documentfoundation.org/show_bug.cgi?id=96343

**Comment by typiconman** [comment]
The problem in LibreOffice seems to be fixed, but you'll need to install the current development build (6.1.0). See my comments here:
https://bugs.documentfoundation.org/show_bug.cgi?id=114681

**Comment by KrasnayaPloshchad** [comment]
So you must waiting 6 months before this bug fix coming, isn’t it?

**Comment by typiconman** [comment]
Well, unfortunately, I have no control over the release cycle for LibreOffice. I'm not even affiliated in any way with The Document Foundation.
If you need the feature immediately, you could install the current (unstable) development version.

**Comment by KrasnayaPloshchad** [comment]
In LibreOffice bugzilla I saw there is a request to back port your patch to 6.0 branch, maybe it could make the feature coming soon.
