### ISSUE TITLE
Ponomar Unicode should provide bold face

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [typiconman/fonts-cu#7]
Seem from [part1_vigil.pdf](http://ponomar.net/files/part1_vigil.pdf), I found several texts also uses Church Typeface, but it looks bolded, especially on page 3: ВЕЧЕ́РНѦ, ОꙊ҆́ТРЕНѦ. It is possible of creating Ponomar Unicode Bold font to implement this face?

**Comment by starover77** [comment]
What you are seeing on page 3 is not bold text. You are seeing two different point sizes. Hypothetically speaking, you are seeing a mixture of 10 point text with 12 point text.

**Comment by KrasnayaPloshchad** [comment]
Please see this sample, I made the comparation via Windows Paint.
![Sample](https://i.imgur.com/kxtfqgg.png)

**Comment by KrasnayaPloshchad** [comment]
I have no idea for whether this issue should reopened, because I found the text МОСКВА̀ looks sightly bolded on the cover, but I’m not sure for my discovery.

**Comment by typiconman** [comment]
Actually, I think that it is possible that a bolded Slavonic typeface exists in some publications (though it certainly wouldn't be traditional). And there may eve be good technical reasons to create one (it would be better than the "bolding" features of various software). However, because it is not used in standard publications and since we have very limited resources, it is not something we will work on.
